---
title: "DonorSearch Aristotle"
output: html_notebook
---
Import libraries
```{r setup}
library(ggplot2)
```

Data Prep:
Load sample data in, limit estimated capacity to $1,000,000 and sample 15,000. Randomly assign Donors and Non-Donors to each row.
```{r data}
constituents <- read.csv(file = "../Data/DonorSearch Aristotle.csv")
sample_constituents <- constituents[constituents$Estimated.Capacity <= 1000000, ]
sample_constituents <- sample_constituents[sample(nrow(sample_constituents), 15000), ]
sample_constituents$Donor.Type <- sample(c("Donor","Non-Donor"), size = nrow(sample_constituents), replace = TRUE)
```

Updates the data to look slightly different for a single iteration
```{r update}
update <- function(df) {
  df$Aristotle.Score <- df$Aristotle.Score+rnorm(nrow(df))
  df$Aristotle.Score[df$Aristotle.Score > 100] <- 100
  df$Aristotle.Score[df$Aristotle.Score <= 0] <- 1
  df$Size <- 1/log(df$Estimated.Capacity + 1)
  df
}
```

Animation:
Create 50 plots that can be used to create the animation.
```{r anim}
for (i in seq(1,50,by=1)){
  sample_constituents <- update(sample_constituents)
  aristotle_scatter <- ggplot(sample_constituents,aes(x = Estimated.Capacity, y = Aristotle.Score, color = Donor.Type, size = Size)) + 
    geom_point(alpha = 0.5) + 
    scale_color_manual(values = c("#DE9934","#31CAE1"), guide = "none") +
    scale_size(guide="none", range = c(1,15)) +
    ylim(0,100) +
    labs(x = "Estimated Capacity", y = "Aristotle Score") + 
    theme_classic() + 
    theme(axis.title = element_text(color = "white"),
          axis.text = element_text(color = "white"),
          axis.line = element_line(color = "white"),
          axis.ticks = element_line(color = "white"),
          panel.background = element_rect(fill = "#303841",colour = NA),
          plot.background = element_rect(fill = "#303841",colour = NA))
  ggsave(paste("../animAristotle/Aristotle_",i,".png",sep=""), aristotle_scatter, bg = "#303841", width = 17.333, height = 7.5, units = "in", dpi = 100)
}
```